using HRPerformance.Domain.Entities;
using HRPerformance.Domain.Enums;
using HRPerformance.Domain.Interfaces;
using HRPerformance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace HRPerformance.Infrastructure.Services;

public class RuleEngineService : IRuleEngineService
{
    private readonly ApplicationDbContext _context;
    private readonly ILogger<RuleEngineService> _logger;

    public RuleEngineService(ApplicationDbContext context, ILogger<RuleEngineService> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task ProcessAttendanceAsync(AttendanceLog log, CancellationToken ct = default)
    {
        if (log.IsProcessed) return;

        decimal totalImpact = 0;
        if (log.IsAbsent)
            totalImpact += await EvaluateRulesAsync(log.OrganizationId, RuleConditionType.Absence, 1, ct);
        else if (log.DelayMinutes > 0)
            totalImpact += await EvaluateRulesAsync(log.OrganizationId, RuleConditionType.Delay, log.DelayMinutes, ct);

        if (totalImpact != 0)
        {
            AddScore(
                log,
                totalImpact,
                log.IsAbsent ? "غیبت" : $"تأخیر {log.DelayMinutes} دقیقه",
                null);
        }

        log.IsProcessed = true;
        log.ProcessedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync(ct);
    }

    public Task ProcessHourlyLeaveAsync(AttendanceLog log, int leaveDurationMinutes, CancellationToken ct = default) =>
        ProcessMisHourlyLeaveAsync(log, leaveDurationMinutes, ct);

    public async Task ProcessMisHourlyLeaveAsync(AttendanceLog log, int leaveDurationMinutes, CancellationToken ct = default)
    {
        if (log.IsProcessed) return;

        var leaveImpact = await EvaluateRulesAsync(log.OrganizationId, RuleConditionType.HourlyLeave, leaveDurationMinutes, ct);
        if (leaveImpact != 0)
            AddScore(log, leaveImpact, $"مرخصی ساعتی {leaveDurationMinutes} دقیقه", log.LeaveType);

        if (log.DelayMinutes > 0)
        {
            var delayImpact = await EvaluateRulesAsync(log.OrganizationId, RuleConditionType.Delay, log.DelayMinutes, ct);
            if (delayImpact != 0)
                AddScore(log, delayImpact, $"تاخیر {log.DelayMinutes} دقیقه (مرخصی اول وقت)", log.LeaveType);
        }

        log.IsProcessed = true;
        log.ProcessedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync(ct);
    }

    public async Task<decimal> EvaluateRulesAsync(Guid organizationId, RuleConditionType type, decimal value, CancellationToken ct = default)
    {
        var rules = await _context.EvaluationRules
            .Where(r => r.OrganizationId == organizationId && r.ConditionType == type && r.IsActive && !r.IsDeleted)
            .ToListAsync(ct);

        foreach (var rule in rules.OrderBy(r => r.Priority))
            if (MatchRule(rule, value))
                return rule.ScoreImpact;

        return 0;
    }

    private void AddScore(AttendanceLog log, decimal impact, string title, string? description)
    {
        var scoreType = impact >= 0 ? ScoreType.Positive : ScoreType.Negative;
        _context.EmployeeScores.Add(new EmployeeScore
        {
            EmployeeId = log.EmployeeId,
            OrganizationId = log.OrganizationId,
            AttendanceLogId = log.Id,
            Score = impact,
            ScoreType = scoreType,
            Title = title,
            Description = description,
            ScoreDate = log.AttendanceDate,
            Year = log.AttendanceDate.Year,
            Month = log.AttendanceDate.Month,
            IsAutoGenerated = true
        });
    }

    private static bool MatchRule(EvaluationRule rule, decimal value) => rule.Operator switch
    {
        RuleOperator.LessThan => value < rule.MinValue,
        RuleOperator.LessOrEqual => value <= rule.MinValue,
        RuleOperator.Equal => value == rule.MinValue,
        RuleOperator.GreaterOrEqual => value >= rule.MinValue,
        RuleOperator.GreaterThan => value > rule.MinValue,
        RuleOperator.Between => value >= rule.MinValue && value <= rule.MaxValue,
        _ => false
    };
}
