using HRPerformance.Entities;
using HRPerformance.Enums;
using HRPerformance.Interfaces;
using HRPerformance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace HRPerformance.Services;
public class RuleEngineService : IRuleEngineService
{
    private readonly ApplicationDbContext _context;
    private readonly ILogger<RuleEngineService> _logger;
    public RuleEngineService(ApplicationDbContext context, ILogger<RuleEngineService> logger) { _context = context; _logger = logger; }

    public async Task ProcessAttendanceAsync(AttendanceLog log, CancellationToken ct = default)
    {
        if (log.IsProcessed) return;
        var rules = await _context.EvaluationRules.Where(r => r.OrganizationId == log.OrganizationId && r.IsActive && !r.IsDeleted).OrderBy(r => r.Priority).ToListAsync(ct);
        decimal totalImpact = 0;
        if (log.IsAbsent) totalImpact += await EvaluateRulesAsync(log.OrganizationId, RuleConditionType.Absence, 1, ct);
        else if (log.DelayMinutes > 0) totalImpact += await EvaluateRulesAsync(log.OrganizationId, RuleConditionType.Delay, log.DelayMinutes, ct);
        if (totalImpact != 0)
        {
            var scoreType = totalImpact >= 0 ? ScoreType.Positive : ScoreType.Negative;
            _context.EmployeeScores.Add(new EmployeeScore {
                EmployeeId = log.EmployeeId, OrganizationId = log.OrganizationId, AttendanceLogId = log.Id,
                Score = totalImpact, ScoreType = scoreType, Title = log.IsAbsent ? "غیبت" : $"تأخیر {log.DelayMinutes} دقیقه",
                ScoreDate = log.AttendanceDate, Year = log.AttendanceDate.Year, Month = log.AttendanceDate.Month, IsAutoGenerated = true
            });
        }
        log.IsProcessed = true; log.ProcessedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync(ct);
    }

    public async Task ProcessHourlyLeaveAsync(AttendanceLog log, int leaveDurationMinutes, CancellationToken ct = default)
    {
        if (log.IsProcessed) return;

        var totalImpact = await EvaluateRulesAsync(log.OrganizationId, RuleConditionType.HourlyLeave, leaveDurationMinutes, ct);
        if (totalImpact != 0)
        {
            var scoreType = totalImpact >= 0 ? ScoreType.Positive : ScoreType.Negative;
            _context.EmployeeScores.Add(new EmployeeScore
            {
                EmployeeId = log.EmployeeId,
                OrganizationId = log.OrganizationId,
                AttendanceLogId = log.Id,
                Score = totalImpact,
                ScoreType = scoreType,
                Title = $"مرخصی ساعتی {leaveDurationMinutes} دقیقه",
                Description = log.LeaveType,
                ScoreDate = log.AttendanceDate,
                Year = log.AttendanceDate.Year,
                Month = log.AttendanceDate.Month,
                IsAutoGenerated = true
            });
        }

        log.IsProcessed = true;
        log.ProcessedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync(ct);
    }

    public async Task<decimal> EvaluateRulesAsync(Guid organizationId, RuleConditionType type, decimal value, CancellationToken ct = default)
    {
        var rules = await _context.EvaluationRules.Where(r => r.OrganizationId == organizationId && r.ConditionType == type && r.IsActive && !r.IsDeleted).ToListAsync(ct);
        foreach (var rule in rules.OrderBy(r => r.Priority))
            if (MatchRule(rule, value)) return rule.ScoreImpact;
        return 0;
    }

    private static bool MatchRule(EvaluationRule rule, decimal value) => rule.Operator switch {
        RuleOperator.LessThan => value < rule.MinValue,
        RuleOperator.LessOrEqual => value <= rule.MinValue,
        RuleOperator.Equal => value == rule.MinValue,
        RuleOperator.GreaterOrEqual => value >= rule.MinValue,
        RuleOperator.GreaterThan => value > rule.MinValue,
        RuleOperator.Between => value >= rule.MinValue && value <= rule.MaxValue,
        _ => false
    };
}
