using HRPerformance.Common;
using HRPerformance.Enums;

namespace HRPerformance.Entities;

public class EmployeeScore
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid EmployeeId { get; set; }
    public Guid OrganizationId { get; set; }
    public Guid? CategoryId { get; set; }
    public Guid? ItemId { get; set; }
    public Guid? RuleId { get; set; }
    public Guid? AttendanceLogId { get; set; }
    public decimal Score { get; set; }
    public ScoreType ScoreType { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public DateTime ScoreDate { get; set; }
    public int Year { get; set; }
    public int Month { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public Guid? CreatedBy { get; set; }
    public Employee? Employee { get; set; }
}
